### PR TITLE
BAH-486 avoid hard coding of locale info

### PR DESCRIPTION
**Pull request by sanishmaharjan**
[BAH-486](https://bahmni.atlassian.net/browse/BAH-486): Avoid hardcoding of default locale & allowed-locales in Bed Management Admin UI App.

@mks-d  Please code review.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@mks-d what do you think of this?

**Comment by dkayiwa** [comment]
@mks-d do you object to merging this?

**Comment by djazayeri** [comment]
I tested this out locally, and it seems to work fine. There are no unit tests, but I can live with that.
I will merge.

**Comment by mks-d** [comment]
@dkayiwa thanks for the reminders, and @djazayeri thanks for taking action. This went completely out of my radar in March/April.

**Pull request merged**
